language: node_js
node_js:
  - 0.10.29
after_script:
  - cat ./coverage/phantomjs/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: heroku
  strategy: git
  app:
    master: readfwd-delta-app
  api_key:
    secure: JSQN3yjoSabN0+ToWUnwRT/N91cBdNjsq5QyRjbEtiiSGpMDhs9dRAlAqaGgs5XielmL9Sny+EHmymLKRBJrwjqwAzSyzwqm+x7uWEBgVYVmF8Bvwsrkv9rvmgyUWDnXjp8a645iCZJ3YwnxzapznEQaqsrT3oYwQFyWTcuxXmU=

